openapi: 3.0.3
info:
  title: PaperCast API
  description: AI 논문 팟캐스트 에피소드 제공 API (읽기 전용)
  version: 1.0.0
  contact:
    name: PaperCast Team
    email: hanseungsoo13@gmail.com
  license:
    name: MIT

servers:
  - url: https://papercast.vercel.app/api
    description: 프로덕션 서버
  - url: http://localhost:3000/api
    description: 로컬 개발 서버

paths:
  /health:
    get:
      summary: 헬스 체크
      description: API 서버 상태 확인
      tags:
        - System
      responses:
        '200':
          description: 정상 동작
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [healthy]
                  timestamp:
                    type: string
                    format: date-time
                  version:
                    type: string

  /episodes:
    get:
      summary: 에피소드 목록 조회
      description: 모든 팟캐스트 에피소드 목록을 날짜 역순으로 반환
      tags:
        - Episodes
      parameters:
        - name: limit
          in: query
          description: 반환할 에피소드 개수
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          description: 건너뛸 에피소드 개수 (페이지네이션)
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  episodes:
                    type: array
                    items:
                      $ref: '#/components/schemas/EpisodeSummary'
                  total:
                    type: integer
                    description: 전체 에피소드 개수
                  limit:
                    type: integer
                  offset:
                    type: integer

  /episodes/latest:
    get:
      summary: 최신 에피소드 조회
      description: 가장 최근에 생성된 에피소드 상세 정보 반환
      tags:
        - Episodes
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EpisodeDetail'
        '404':
          description: 에피소드 없음
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /episodes/{episode_id}:
    get:
      summary: 특정 에피소드 조회
      description: ID로 특정 에피소드 상세 정보 반환
      tags:
        - Episodes
      parameters:
        - name: episode_id
          in: path
          required: true
          description: 에피소드 ID (YYYY-MM-DD 형식)
          schema:
            type: string
            pattern: '^\d{4}-\d{2}-\d{2}$'
          example: "2025-01-27"
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EpisodeDetail'
        '404':
          description: 에피소드 없음
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    EpisodeSummary:
      type: object
      description: 에피소드 요약 정보
      required:
        - id
        - title
        - publication_date
        - audio_url
        - papers_count
        - created_at
      properties:
        id:
          type: string
          pattern: '^\d{4}-\d{2}-\d{2}$'
          example: "2025-01-27"
        title:
          type: string
          example: "Daily Papers - 2025-01-27"
        publication_date:
          type: string
          format: date
          example: "2025-01-27"
        audio_url:
          type: string
          format: uri
          example: "https://storage.googleapis.com/papers_ethan/2025-01-27/episode.mp3"
        duration_seconds:
          type: integer
          nullable: true
          example: 627
        file_size_bytes:
          type: integer
          nullable: true
          example: 5026816
        papers_count:
          type: integer
          default: 3
          example: 3
        created_at:
          type: string
          format: date-time
          example: "2025-01-27T06:00:00Z"

    EpisodeDetail:
      allOf:
        - $ref: '#/components/schemas/EpisodeSummary'
        - type: object
          properties:
            description:
              type: string
              nullable: true
              example: "오늘의 Hugging Face 트렌딩 논문 Top 3"
            script:
              type: string
              nullable: true
              example: "안녕하세요, 오늘의 AI 논문 팟캐스트입니다..."
            papers:
              type: array
              items:
                $ref: '#/components/schemas/Paper'
              minItems: 3
              maxItems: 3

    Paper:
      type: object
      description: 논문 정보
      required:
        - id
        - title
        - authors
        - url
      properties:
        id:
          type: string
          example: "2510.19338"
        title:
          type: string
          example: "Every Attention Matters"
        authors:
          type: array
          items:
            type: string
          example: ["John Doe", "Jane Smith"]
        abstract:
          type: string
          nullable: true
          example: "We propose a novel approach..."
        summary:
          type: string
          nullable: true
          example: "이 논문은 대규모 언어 모델의..."
        url:
          type: string
          format: uri
          example: "https://huggingface.co/papers/2510.19338"
        arxiv_id:
          type: string
          nullable: true
          pattern: '^\d{4}\.\d{4,5}$'
          example: "2510.19338"
        categories:
          type: array
          items:
            type: string
          nullable: true
          example: ["cs.CL", "cs.AI"]
        upvotes:
          type: integer
          minimum: 0
          default: 0
          example: 142
        thumbnail_url:
          type: string
          format: uri
          nullable: true
        published_date:
          type: string
          nullable: true
          example: "2025-01-26"
        collected_at:
          type: string
          format: date-time
          example: "2025-01-27T05:00:00Z"

    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          example: "NotFound"
        message:
          type: string
          example: "에피소드를 찾을 수 없습니다"
        details:
          type: object
          nullable: true

tags:
  - name: System
    description: 시스템 상태 확인
  - name: Episodes
    description: 팟캐스트 에피소드 조회
