name: Deploy API to Cloud Run

on:
  push:
    branches:
      - main
    # API 폴더 내부의 파일이 변경되었을 때만 이 워크플로우를 실행합니다.
    paths:
      - 'api/**'

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_DEPLOY }}' # API 배포용 GSA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy podcast-backend-api \
            --source API/ \
            --region asia-northeast3 \
            --allow-unauthenticated \
            --project ${{ secrets.GCP_PROJECT_ID }}